twig:
  file_name_pattern: '*.twig'
  form_themes:
    - '@SpiriitFormFilter/Form/form_div_layout.html.twig'

spiriit_form_filter:
  listeners:
    doctrine_orm: true
    doctrine_dbal: false

when@test:
  twig:
    strict_variables: true
